---
block:
- name: Install IIS (Web-Server) and management tools 
  win_feature:
    name: Web-Server
    state: present
    include_management_tools: yes 
  register: win_feature_output 
- name: Reboot if installing Web-Server feature requires it
  win_reboot:
  when: win_feature_output.reboot_required
tags: iisfeatureinstall 
 