---
# tasks file for windows-install-webserver
 - name: '[WINDOWS_INSTALL_WEB_SERVER][MAIN] Gather facts' 
   import_tasks: recollect_facts.yml
 - name: '[WINDOWS_INSTALL_WEB_SERVER][MAIN] Install, configure IIS and check website' 
   block:   
    - name: '[WINDOWS_INSTALL_WEB_SERVER][MAIN] Install IIS'
      import_tasks: install_iis.yml
    - name: ' [WINDOWS_INSTALL_WEB_SERVER][MAIN] Create website index.html' 
      import_tasks: create_index.yml
    - name: '[WINDOWS_INSTALL_WEB_SERVER][MAIN] Check URL http://localhost' 
      import_tasks: test_url.yml
   when: ansible_facts['distribution_version'] >= '10' 
   